services:
  mysql-db-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsASampleRootPassword
      MYSQL_USER: mysqluser
      MYSQL_DATABASE: test-database
      MYSQL_PASSWORD: thisIsASampleUserPassword
    ports:
      - "3306:3306"
  
  sut:
    container_name: go-worker-sut
    depends_on:
      - mysql-db-1
    environment:
      ENVIRONMENT: test
      PORT: 8080
      LOG_APP_CONFIG_AT_STARTUP: 0
      SUPRESS_SECRETS_IN_STARTUP_LOGS: 1
      MYSQL_CONNECTION_STRING: root:thisIsASampleRootPassword@tcp(mysql-db-1:3306)/test-database?parseTime=true
    build:
      context: .
      dockerfile: ./test/Dockerfile
    volumes:
      - "./test:/app/test"
    entrypoint: [ "bash", "-c", "go test ./test/..."]

networks:
  default:
    name: dev_network
    driver: bridge
    external: true