services:
  mysql-db-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsASampleRootPassword
      MYSQL_USER: mysqluser
      MYSQL_DATABASE: mysql-db
      MYSQL_PASSWORD: thisIsASampleUserPassword
    ports:
      - "3306:3306"
  
  go-service:
    container_name: worker
    depends_on:
      - mysql-db-1
    build:
      dockerfile: ./Dockerfile

networks:
  default:
    name: dev_network
    driver: bridge
    external: true