services:
  mysql-db-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thisIsASampleRootPassword
      MYSQL_USER: mysqluser
      MYSQL_DATABASE: sample-database
      MYSQL_PASSWORD: thisIsASampleUserPassword
    ports:
      - "3306:3306"
  
  go-service:
    container_name: worker
    depends_on:
      - mysql-db-1
    environment:
      ENVIRONMENT: local
      LOG_APP_CONFIG_AT_STARTUP: 1
      SUPRESS_SECRETS_IN_STARTUP_LOGS: 1
      MYSQL_CONNECTION_STRING: root:thisIsASampleRootPassword@tcp(mysql-db-1:3306)/sample-database?parseTime=true
    build:
      dockerfile: ./Dockerfile

networks:
  default:
    name: dev_network
    driver: bridge
    external: true