#
# This workflow runs the automated test suite for the Go program.
# The tests are containerised and connect to a local MySQL container on the same network as the Go worker.
#

name: Test Go Code

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  ENVIRONMENT: test
  PORT: 8080
  LOG_APP_CONFIG_AT_STARTUP: 0

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |          
          : # Docker networks for CI testing
          docker network create dev_network
      
      - name: Run Go tests
        run: |
          docker compose down -v
          docker-compose -f docker-compose.ci.yml up --remove-orphans --force-recreate --build --exit-code-from sut