name: Test Go Code

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

env:
  ENVIRONMENT: test
  LOG_APP_CONFIG_AT_STARTUP: 0

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |          
          : # Docker networks for CI testing
          docker network create dev_network
      
      - name: Run Go tests
        run: |
          docker compose down -v
          docker-compose -f docker-compose.ci.yml up --remove-orphans --force-recreate --build --exit-code-from sut